name: ci

on:
  push:
    tags:
      - '*.*.*'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set - Tag
        id: set-tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
                      
      - name: SETUP - QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: DOCKER - Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}
          registry: silvester.jfrog.io
        
      - name: SETUP - Docker
        uses: docker/setup-buildx-action@v1
        
      - name: DOCKER - Build & Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            artifactoryUsername=${{ secrets.ARTIFACTORY_USERNAME }}
            artifactoryPassword=${{ secrets.ARTIFACTORY_PASSWORD }}
          tags: |
            silvester.jfrog.io/silvester-docker/file-compression:${{ steps.set-tag.outputs.tag }}
            silvester.jfrog.io/silvester-docker/file-compression:latest